# Generated by Django 4.2.14 on 2025-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodychain',
            name='consecutive',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Consecutivo'),
        ),
        migrations.AddField(
            model_name='historicalcustodychain',
            name='consecutive',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Consecutivo'),
        ),
        migrations.AlterField(
            model_name='custodychain',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='custodychain',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='custodychain',
            name='time_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas Totales'),
        ),
        migrations.AlterField(
            model_name='historicalcustodychain',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='historicalcustodychain',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='historicalcustodychain',
            name='time_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas Totales'),
        ),
    ]
