# Generated by Django 4.2.14 on 2025-08-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_custodychain_consecutive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Proyecto', 'verbose_name_plural': 'historical Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
