const idProject = window.djangoConfig?.projectId ?? 62
const apiBaseUrl = window.djangoConfig?.baseUrl ?? "http://localhost:8000"
const csrfToken = window.djangoConfig?.csrfToken ?? "falsocsrf"

export const appConfig = {
    "apiBaseUrl": apiBaseUrl,
    "csrfToken": csrfToken,
    "idProject": idProject,
    "urlLogo": apiBaseUrl + "/static/img/logo.png",
    "headers": {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "X-CSRFToken": csrfToken
    },
    "URLProjectData": apiBaseUrl + "/api/projects/all-info/" + idProject + "/",
    "URLSourcesAvailable": apiBaseUrl + "/api/projects/resources/available/",
    "URLTechnicalsAvailable": apiBaseUrl + "/api/technicals/avaliables/",
    "URLVehiclesAvailable": apiBaseUrl + "/api/vehicles/avaliables/",
    "URLResourcesProject": apiBaseUrl + "/api/projects/" + idProject + "/resources/",
    "URLUpdateResourceItem": apiBaseUrl + "/api/projects/resources/update/",
    "URLDeleteResourceProject": apiBaseUrl + "/api/projects/resources/delete/${id_project_resource}/",
    "URLSheetProjects": apiBaseUrl + "/api/workorders/sheets/project/" + idProject + "/",
    "URLAddSheetProject": apiBaseUrl + "/api/workorders/sheets/create/",
    "URLUpdateSheetProject": apiBaseUrl + "/api/workorders/sheets/update/",
    "URLReopenSheetProject": apiBaseUrl + "/api/workorders/sheets/reopen/",
    "URLUpdateSheetDetailDays": apiBaseUrl + "/api/workorders/sheets/detail/${detailId}/days/",
    "URLAddResourceToProject": apiBaseUrl + "/api/projects/resources/add/",
    "URLCreateCustodyChain": apiBaseUrl + "/api/workorders/custody_chain/create/",
    "URLCustodyChainDetail": apiBaseUrl + "/api/workorders/custody_chain/detail/${id}/",
    "URLUpdateCustodyChain": apiBaseUrl + "/api/workorders/custody_chain/${id}/edit/",
    "PDFCustodyChainReport": apiBaseUrl + "/reports/custody-chain/${id}/",
    "PDFCertFinalDisposition" : apiBaseUrl + "/reports/final-disposition/${id}/",
    "URLWorkSheetReport": apiBaseUrl + "/reports/worksheet/${id}/",
    "URLReleaseResource": apiBaseUrl + "/api/projects/resources/release/",
    "URLLoadFiles": apiBaseUrl + "/api/load_files/",
    "URLProjectDocTree": apiBaseUrl + "/api/load_files/project/" + idProject + "/tree/",
    "URLProjectDocMerge": apiBaseUrl + "/api/load_files/project/" + idProject + "/merge/",
    "URLProjectBulkCustody": apiBaseUrl + "/api/load_files/project/" + idProject + "/bulk_custody/",
    "URLCloseProject": apiBaseUrl + "/api/projects/" + idProject + "/close/",
    "URLShippingGuides": apiBaseUrl + "/api/shipping/guides/",
    "URLShippingGuideDetail": apiBaseUrl + "/api/shipping/guides/${id}/",
    "URLShippingGuideDelete": apiBaseUrl + "/api/shipping/guides/${id}/delete/",
    "URLShippingGuideDownload": apiBaseUrl + "/reports/shipping-guide/${id}/",
    "URLMaintenanceSheets": apiBaseUrl + "/api/maintenance/sheets/",
    "URLMaintenanceSheetDetail": apiBaseUrl + "/api/maintenance/sheets/${id}/",
    "URLMaintenanceSheetDelete": apiBaseUrl + "/api/maintenance/sheets/${id}/delete/",
    "URLMaintenanceSheetDownload": apiBaseUrl + "/reports/sheet-maintenance/${id}/",
}